global:
  cluster: kind-argo-dev
  image:
    repository: ghcr.io/ranodev78/weather-app
    tag: sha-fc78d6f
    pullPolicy: IfNotPresent
  host: localhost
  autoscaler:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
  disruptionBudget:
    enabled: false
    minAvailable: 1
  resourceLimits:
    cpu: 500m
    memory: 512Mi

# Austin instance configuration
weather-app-austin:
  enabled: true
  name: weather-app-austin
  env:
    location: "Austin, Texas"
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8080
  replicaCount: 2

# Boston instance configuration
weather-app-boston:
  enabled: true
  name: weather-app-boston
  env:
    location: "Boston, Massachusetts"
  service:
    type: ClusterIP
    port: 8082
    targetPort: 8080
  replicaCount: 2