global:
  namespace: weather-apps-dev
  cluster: kind-argo-dev
  image:
    repository: ranodev78/weather-app
    tag: sha-9751ae8
    pullPolicy: IfNotPresent
  host: localhost
  autoscaler:
    enabled: false
    minReplicas: 2
    maxReplicas: 3
  disruptionBudget:
    enabled: false
    minAvailable: 1
  resourceLimits:
    cpu: 100m
    memory: 128Mi

# Austin instance configuration
austin:
  enabled: true
  name: weather-app-austin
  service:
    type: ClusterIP
    port: 8080
  replicaCount: 2

# Boston instance configuration
boston:
  enabled: true
  name: weather-app-boston
  service:
    type: ClusterIP
    port: 8081
  replicaCount: 2