apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
    version: {{ .Values.global.image.tag }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        version: {{ .Values.global.image.tag }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.global.image.repository }}:{{ .Values.global.image.tag }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: LOCATION
              value: "{{ .Values.env.location | quote }}"
          {{- if .Values.global.resourceLimits }}
          resources:
            limits:
              cpu: {{ .Values.global.resourceLimits.cpu }}
              memory: {{ .Values.global.resourceLimits.memory }}
            requests:
              cpu: {{ .Values.global.resourceLimits.cpu }}
              memory: {{ .Values.global.resourceLimits.memory }}
          {{- end }}
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 60      
            periodSeconds: 20            
            timeoutSeconds: 3            
            successThreshold: 1          
            failureThreshold: 5         
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 45      
            periodSeconds: 10            
            timeoutSeconds: 3            
            successThreshold: 1          
            failureThreshold: 5         
